---
version: "2.1"
services:
  radarr-fixer-after-filebot:
    container_name: mangrana_java_radarr_fix
    image: radarr-fixer-after-filebot:latest
    build: .
    volumes:
      - ${USER_HOME}/logs/filebot:/filebot_logs
      - ./config:/config